#! /bin/sh -

#
# Copyright (C) 2019-2024 Stealth Software Technologies, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an "AS
# IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
# express or implied. See the License for the specific language
# governing permissions and limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
#

#-----------------------------------------------------------------------
# Include the SST Bash library
#-----------------------------------------------------------------------
#
# Include the first sst.bash file found by searching up the directory
# tree starting from the location of this script file. If no such file
# is found, fall back to including plain sst.bash with PATH resolution.
#
# This section is written in portable shell to ensure it works properly
# in any shell.
#

case ${SST_SEARCH_UP_X-} in '')
  case $0 in /*)
    SST_SEARCH_UP_X=$0
  ;; *)
    SST_SEARCH_UP_X=./$0
  esac
  SST_SEARCH_UP_R='\(.*/\)'
  SST_SEARCH_UP_X=`
    expr "x${SST_SEARCH_UP_X?}" : "x${SST_SEARCH_UP_R?}"
  `. || exit $?
  unset SST_SEARCH_UP_R
  SST_SEARCH_UP_X=`
    cd "${SST_SEARCH_UP_X?}" || exit $?
    while :; do
      if test -f sst.bash; then
        case ${PWD?} in *[!/]*)
          printf '%s\n' "${PWD?}"/ || exit $?
        ;; *)
          printf '%s\n' "${PWD?}" || exit $?
        esac
        exit
      fi
      case ${PWD?} in *[!/]*)
        cd ..
      ;; *)
        exit
      esac
    done
  ` || exit $?
  export SST_SEARCH_UP_X
esac
set -e || exit $?
. "${SST_SEARCH_UP_X?}"sst.bash
unset SST_SEARCH_UP_X

#-----------------------------------------------------------------------

main() {

  sst_ubuntu_install_raw lsb-release

  v=$(lsb_release -r | sed 's/^[^0-9]*//')
  case $v in (x)
    sst_barf "Unsupported Ubuntu version: $v"
  ;; (18.0[4-9]* | 18.[1-9]* | 19.* | 20.0[0-3]*)
    v=18.04
  ;; (20.0[4-9]* | 20.[1-9]* | 21.* | 22.0[0-3]*)
    v=20.04
  ;; (22.0[4-9]* | 22.[1-9]* | 23.* | 24.0[0-3]*)
    v=22.04
  ;; (*)
    sst_barf "Unsupported Ubuntu version: $v"
  esac
  readonly v

  on_x=on-ubuntu-$v
  export on_x

  s=src/install/$from_w/$on_x
  readonly s

  if [[ ! -f "$s" && ! -h "$s" ]]; then
    sst_barf 'Unsupported Ubuntu version: %s' "$v"
  fi

  "$s" "$@"

}; readonly -f main

main "$@"
