#! /bin/sh -
#
# Copyright (C) 2019-2024 Stealth Software Technologies, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an "AS
# IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
# express or implied. See the License for the specific language
# governing permissions and limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
#
# This script uses the SST Bash library to bootstrap from /bin/sh into
# bash. See the Bash library > Bootstrapping section of the SST manual
# for more information.
#

set -e || exit $?
. src/bash/sst.bash

sst_ac_start build-aux/autogen.ac
sst_am_start build-aux/autogen.am

#-----------------------------------------------------------------------

sst_ag_define_ordering_macros

sst_ag_call_defun_once_macros

#-----------------------------------------------------------------------
# Root .ag includes
#-----------------------------------------------------------------------
#
# If an .ag file needs to be included and there's no more specific .ag
# file in which to do it, then do it here.
#

sst_ag_include \
  doc/manual/build.phony.ag \
  doc/pages/build.phony.ag \
  doc/readme/build.phony.ag \
  src/android/carma-ARCH-linux-android-apiLEVEL/ag \
  src/artifactory/build.phony.ag \
  src/core/build.phony.ag \
  src/docker/kestrel-build/build.phony.ag \
  src/docker/kestrel-loop/build.phony.ag \
  src/docker/kestrel/build.phony.ag \
  src/web/build.phony.ag \
;

#-----------------------------------------------------------------------
# Root distributed files
#-----------------------------------------------------------------------
#
# If a file needs to be distributed (i.e., included in the distribution
# archive) and there's no more specific .ag, .ac, or .am file in which
# to do it, then do it here.
#

sst_am_distribute_if_not_dir \
  .clang-format \
  LICENSE \
  RACE_CARMA_GUIDE.adoc \
  README.adoc \
  build-aux/ARTIFACTORY_REVISION \
  build-aux/ARTIFACTORY_REVISION.sh \
  build-aux/RACE_VERSION \
  build-aux/RACE_VERSION.sh \
  build-aux/RIB_VERSION \
  build-aux/RIB_VERSION.sh \
  build-aux/carma.srcdir \
  build-aux/gatbps-echo.sh \
  build-aux/gatbps-gen-date.sh \
  build-aux/gatbps-gen-date.sh.cache \
  build-aux/gatbps-gen-libtool-c.sh \
  build-aux/gatbps-gen-libtool-c.sh.cache \
  build-aux/gatbps-gen-version.docker.sh \
  build-aux/gatbps-gen-version.docker.sh.args \
  build-aux/gatbps-gen-version.docker.sh.cache \
  build-aux/gatbps-gen-version.sh \
  build-aux/gatbps-gen-version.sh.args \
  build-aux/gatbps-gen-version.sh.cache \
  build-aux/gen-configure.sh \
  install/**/* \
  src/bash/include/**/* \
  src/bash/scripts/gitlab-ci \
  src/bash/sst.bash \
  src/install/**/* \
  src/rib/rib.sh \
  src/sh/**/* \
  sst.bash \
;

#-----------------------------------------------------------------------

sst_ajh_download build-aux/downloads
sst_ajh_gitbundle build-aux/gitbundles
sst_ajh_c_cpp_test test src/core/libcarma.la
autogen_texinfo doc/carma.texi doc/texi

sst_ag_install_bash_library src/bash

sst_ac_finish
sst_am_finish

#-----------------------------------------------------------------------

x='autoreconf -f -i -v -W all'
sst_info "Running: $x"
$x
