//
// Copyright (C) 2019-2024 Stealth Software Technologies, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an "AS
// IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language
// governing permissions and limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0
//

[#cro_{jhezqkco_type_short}_count]
= The `--{jhezqkco_type_short}-count` option

[source,subs="{sst_subs_source}"]
----
{jhezqkco_attr}=\({jhezqkco_a}\)
{jhezqkco_attr}=\({jhezqkco_a}\)/\({jhezqkco_b}\)
----

The `{jhezqkco_attr}` option specifies the expected number of servers
\({jhezqkco_n}\) that will be probabilistically selected to become
{jhezqkco_type_long} servers at genesis time.

If \({jhezqkco_b}\) is omitted, the expected number of
{jhezqkco_type_long} servers will be \({jhezqkco_n} = {jhezqkco_a}\),
which must be a nonnegative integer.
Otherwise, \({jhezqkco_a}\) and \({jhezqkco_b}\) must be integers such
that \({jhezqkco_b} > 0\) and \(0 \le {jhezqkco_a} \le {jhezqkco_b}\),
and the expected number of {jhezqkco_type_long} servers will be
\({jhezqkco_n} = ({jhezqkco_a} / {jhezqkco_b}) \cdot s\), where stem:[s]
is the total number of servers.

//
