//
// Copyright (C) 2019-2024 Stealth Software Technologies, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an "AS
// IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language
// governing permissions and limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0
//

//----------------------------------------------------------------------
ifdef::define_attributes[]
ifndef::SECTIONS_CREATE_PLUGIN_TA2_ADOC[]
:SECTIONS_CREATE_PLUGIN_TA2_ADOC:
//----------------------------------------------------------------------

:create_plugin_ta2_name0: create_plugin_ta2

:create_plugin_ta2_id: create-ta2-plugin
:create_plugin_ta2_url: sections/create_plugin_ta2.adoc#{create_plugin_ta2_id}

:create_plugin_ta2_chop0: xref:{create_plugin_ta2_url}[{create_plugin_ta2_name0}]

:create_plugin_ta2: {create_plugin_ta2_chop0}

:pfjbmct4:

//----------------------------------------------------------------------
endif::[]
endif::[]
ifndef::define_attributes[]
//----------------------------------------------------------------------

[#{create_plugin_ta2_id}]
= The `{create_plugin_ta2_name0}` function

[source,subs="{sst_subs_source}"]
----
void {create_plugin_ta2}(
  {kestrel_ta2_sdk} *    sdk,
  {kestrel_ta2_plugin} * plugin
);
----

The `{create_plugin_ta2}` function creates an instance of the TA2
plugin, filling in the `{kestrel_ta2_plugin}` structure pointed to by
`plugin` as follows:

* {empty}
`plugin++->++{kestrel_ta2_plugin_plugin_chop1}` should be an opaque
pointer to the plugin instance.

* {empty}
`plugin++->++{kestrel_ta2_plugin_name_chop1}` should point to a
null-terminated string that contains the plugin name.

* {empty}
All function pointers in `*plugin` should point to the appropriate
plugin functions.

The `sdk` parameter points to a `{kestrel_ta2_sdk}` structure that the
plugin instance can use throughout its lifetime to make calls to
Kestrel.
The structure contains a set of function pointers but no opaque pointer
to the SDK instance, as the `sdk` pointer itself serves as the opaque
pointer.
When the plugin instance calls an SDK function, it should always pass
the `sdk` pointer as the first argument.
For example, the plugin instance could call
`sdk++->++{kestrel_ta2_sdk_get_entropy_chop1}(sdk, p, n)` to fill `p`
with `n` random bytes.

To indicate failure, the `{create_plugin_ta2}` function should set
`plugin++->++{kestrel_ta2_plugin_plugin_chop1}` to a null pointer.
In this case, Kestrel will ignore all of the function pointers in
`*plugin`, but Kestrel will still inspect
`plugin++->++{kestrel_ta2_plugin_name_chop1}`.
If `plugin++->++{kestrel_ta2_plugin_name_chop1}` is not a null pointer,
it should point to an error message that explains why
`{create_plugin_ta2}` failed.
The error message should be null-terminated and encoded in UTF-8.
Although failure is being indicated, Kestrel will still call
`{destroy_plugin_ta2}(plugin)`, allowing any necessary cleanup to be
performed on `plugin++->++{kestrel_ta2_plugin_name_chop1}`.

:vjeaduep: {create_plugin_ta2}
:vjeaduep_name0: {create_plugin_ta2_name0}
include::../partials/choose_your_own_function_name.adoc[]

:enfppyns_a: {create_plugin_ta2}
:enfppyns_a_kind: function
:enfppyns_b: {createPluginTa2}
:enfppyns_b_kind: function
include::../partials/race_cpp_api_correspondence.adoc[]

//----------------------------------------------------------------------
endif::[]
