#
# Copyright (C) 2019-2024 Stealth Software Technologies, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an "AS
# IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
# express or implied. See the License for the specific language
# governing permissions and limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
#

FROM kestrel-build:@PACKAGE_VERSION_DOCKER@

ARG DOCKERFILE_THREADS
ENV DOCKERFILE_THREADS=${DOCKERFILE_THREADS?}

COPY carma.tar.gz /x/carma2.tar.gz

RUN : \
  && cd /x/carma/* \
  && tar -x \
       -f ../../carma2.tar.gz \
       --newer ../../carma.tar.gz \
       --strip-components 1 \
  && make -j${DOCKERFILE_THREADS?} \
  && make install \
;
