#
# Copyright (C) 2019-2024 Stealth Software Technologies, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an "AS
# IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
# express or implied. See the License for the specific language
# governing permissions and limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
#

#
# sst_ac_start [<file>]
#
# Start constructing an accumulative Autoconf source file in which to
# collect autogen output. <file> should specify a file that lives either
# in or below the current directory. If <file> is not given, it defaults
# to autogen.ac.
#

sst_ac_start() {

  # Bash >=4.2: declare -g    autogen_ac_file
  # Bash >=4.2: declare -g    sst_ac_start_has_been_called

  if [[ "${sst_ac_start_has_been_called-}" ]]; then
    sst_barf "sst_ac_start has already been called."
  fi
  readonly sst_ac_start_has_been_called=1

  if (($# == 0)); then
    autogen_ac_file=autogen.ac
  elif (($# == 1)); then
    autogen_ac_file=$1
  else
    sst_expect_argument_count $# 0-1
  fi

  autogen_ac_file=$(sst_add_slash_abs_prefix "$autogen_ac_file")
  autogen_ac_file=${autogen_ac_file%/}
  readonly autogen_ac_file

  cat >$autogen_ac_file <<EOF
dnl
dnl Copyright (C) 2019-2024 Stealth Software Technologies, Inc.
dnl
dnl Licensed under the Apache License, Version 2.0 (the "License");
dnl you may not use this file except in compliance with the License.
dnl You may obtain a copy of the License at
dnl
dnl     http://www.apache.org/licenses/LICENSE-2.0
dnl
dnl Unless required by applicable law or agreed to in writing,
dnl software distributed under the License is distributed on an "AS
dnl IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
dnl express or implied. See the License for the specific language
dnl governing permissions and limitations under the License.
dnl
dnl SPDX-License-Identifier: Apache-2.0
dnl

dnl
dnl This file was generated by ./autogen.
dnl

[

EOF

  sst_trap_append '
    case $sst_trap_entry_status in
      0)
        case ${sst_ac_finish_has_been_called+x} in
          "")
            sst_barf "you forgot to call sst_ac_finish"
          ;;
        esac
      ;;
    esac
  ' EXIT

}; readonly -f sst_ac_start
