#! /bin/sh -

#
# Copyright (C) 2019-2024 Stealth Software Technologies, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an "AS
# IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
# express or implied. See the License for the specific language
# governing permissions and limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
#

#
# All install/* scripts should be identical copies of each other. Do not
# change them into symbolic links to one master copy, as symbolic links
# may not be supported by all environments supported by this script.
#

if test -f src/install/on-x; then
  :
else
  cat <<EOF >&2
$0: Error: You must run this script from the root of the project.
EOF
  exit 1
fi

case $# in 0)
  exec src/install/on-x "$0" || exit $?
;; *)
  exec src/install/on-x "$0" "$@" || exit $?
esac
